services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: unless-stopped
    shm_size: 256mb
    volumes:
    - ./frigate/config.yml:/config/config.yml
    - frigate_db:/config
    - ./media:/media/frigate
    - /etc/localtime:/etc/localtime:ro
    ports:
    - 5000:5000
    - 1984:1984
    - 8554:8554
    - 8555:8555/tcp
    - 8555:8555/udp
    environment:
      FRIGATE_RTSP_PASSWORD: ''
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    depends_on:
    - mosquitto
    networks:
    - swarmcam
    runtime: nvidia
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    restart: unless-stopped
    volumes:
    - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    - ./mosquitto/data:/mosquitto/data
    - ./mosquitto/log:/mosquitto/log
    ports:
    - 1883:1883
    - 9001:9001
    networks:
    - swarmcam
  dashboard:
    container_name: swarmcam-dashboard
    image: nginx:alpine
    restart: unless-stopped
    volumes:
    - ../dashboard:/usr/share/nginx/html:ro
    ports:
    - 80:80
    networks:
    - swarmcam
volumes:
  frigate_db: null
networks:
  swarmcam:
    driver: bridge
