services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: unless-stopped
    shm_size: 256mb
    volumes:
    - ./frigate/config.yml:/config/config.yml
    - frigate_db:/config
    - ./media:/media/frigate
    - /etc/localtime:/etc/localtime:ro
    network_mode: host
    environment:
      FRIGATE_RTSP_PASSWORD: ''
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    depends_on:
    - mosquitto
    runtime: nvidia
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    restart: unless-stopped
    volumes:
    - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    - ./mosquitto/data:/mosquitto/data
    - ./mosquitto/log:/mosquitto/log
    ports:
    - 1883:1883
    - 9001:9001
    networks:
    - swarmcam
  backend:
    container_name: swarmcam-backend
    build:
      context: ..
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    network_mode: host
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./frigate/config.yml:/swarmcam/docker/frigate/config.yml
    - ./docker-compose.yml:/swarmcam/docker/docker-compose.yml:ro
    - ./media:/swarmcam/docker/media
    - ../backend/aliases.json:/swarmcam/backend/aliases.json
    environment:
      FRIGATE_URL: http://localhost:5000
      MQTT_HOST: localhost
    depends_on:
    - mosquitto
  dashboard:
    container_name: swarmcam-dashboard
    build:
      context: ../frontend
    restart: unless-stopped
    network_mode: host
    depends_on:
    - backend
volumes:
  frigate_db: null
networks:
  swarmcam:
    driver: bridge
