auth:
  enabled: true
mqtt:
  enabled: true
  host: localhost
  port: 1883
detectors:
  cpu1:
    type: cpu
    num_threads: 3
objects:
  track:
  - person
  - car
  - cat
  - dog
  filters:
    person:
      min_score: 0.4
      threshold: 0.5
record:
  enabled: true
  alerts:
    retain:
      days: 14
  detections:
    retain:
      days: 14
  continuous:
    days: 0
  motion:
    days: 7
snapshots:
  enabled: true
  timestamp: true
  bounding_box: false
  retain:
    default: 14
cameras:
  cam_10_42_0_172:
    ffmpeg:
      inputs:
      - path: rtsp://10.42.0.172:8080/h264_ulaw.sdp
        roles:
        - detect
        - record
        input_args: -rtsp_transport tcp -fflags +genpts+discardcorrupt -avoid_negative_ts
          make_zero
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
version: 0.17-0
semantic_search:
  enabled: false
  model_size: small
face_recognition:
  enabled: true
  model_size: small
lpr:
  enabled: false
classification:
  bird:
    enabled: false
